import { Category, Product, Review } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'ebook',
    name: 'E-Book & Panduan',
    slug: 'ebook',
    description: 'Buku digital praktis, panduan tech, bisnis, dan self-growth',
    icon: 'BookOpen',
  },
  {
    id: 'ui-kit',
    name: 'UI Kit & Desain',
    slug: 'ui-kit',
    description: 'Desain Figma, icon pack, mobile app mockup, dan wireframe',
    icon: 'Layout',
  },
  {
    id: 'source-code',
    name: 'Source Code & Template',
    slug: 'source-code',
    description: 'Boilerplate SaaS, starter kit Next.js, script & automation bot',
    icon: 'Code2',
  },
  {
    id: 'preset',
    name: 'Preset & Audio Asset',
    slug: 'preset',
    description: 'Lightroom preset, LUTs video color grading, sample pack audio',
    icon: 'Sliders',
  },
  {
    id: 'template',
    name: 'Template & Dokumen',
    slug: 'template',
    description: 'Notion workspace, spreadsheet finansial, dan pitch deck siap pakai',
    icon: 'FileText',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    seller_id: 'user-seller-1',
    seller_name: 'DevCraft Studio',
    name: 'The Modern Fullstack Next.js 14 Playbook',
    slug: 'modern-fullstack-nextjs-playbook',
    description: 'Panduan lengkap dan praktis membangun aplikasi SaaS modern menggunakan Next.js App Router, TypeScript, Tailwind CSS, Prisma, dan Server Actions dari nol hingga production deployment. Dilengkapi studi kasus real-world dan best practices arsitektur scalable.',
    price: 149000,
    category: 'ebook',
    thumbnail_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    file_url: '/api/download/prod-1',
    file_name: 'NextJS_Playbook_DevCraft_v2.pdf',
    file_size: '18.4 MB (PDF + Code Repo Zip)',
    tags: ['nextjs', 'react', 'ebook', 'fullstack', 'typescript'],
    status: 'active',
    sales_count: 142,
    rating: 4.9,
    rating_count: 38,
    created_at: '2025-01-15T08:00:00Z',
    updated_at: '2025-01-15T08:00:00Z',
  },
  {
    id: 'prod-2',
    seller_id: 'user-seller-2',
    seller_name: 'Studio Minimal',
    name: 'Nexus UI - Minimalist Dashboard & Web App Kit',
    slug: 'nexus-ui-minimalist-dashboard-kit',
    description: 'Koleksi 180+ komponen dashboard siap pakai dan 40+ responsive page layouts di Figma. Dibuat dengan Auto-Layout 5.0, variables token terstandarisasi, mode dark & light, serta responsive typography scale.',
    price: 299000,
    category: 'ui-kit',
    thumbnail_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    file_url: '/api/download/prod-2',
    file_name: 'NexusUI_DesignSystem_Figma.fig',
    file_size: '42.1 MB (.fig file)',
    tags: ['figma', 'ui-kit', 'dashboard', 'minimal', 'design-system'],
    status: 'active',
    sales_count: 98,
    rating: 4.8,
    rating_count: 24,
    created_at: '2025-01-18T10:30:00Z',
    updated_at: '2025-01-18T10:30:00Z',
  },
  {
    id: 'prod-3',
    seller_id: 'user-seller-1',
    seller_name: 'DevCraft Studio',
    name: 'SaaS QuickLaunch - Next.js & Auth Boilerplate',
    slug: 'saas-quicklaunch-boilerplate',
    description: 'Production-ready boilerplate untuk meluncurkan micro-SaaS dalam hitungan jam. Termasuk integrasi Auth, multi-tenancy, database schema migrations, transactional emails, SEO metatags, dan mock payment gateway.',
    price: 450000,
    category: 'source-code',
    thumbnail_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    file_url: '/api/download/prod-3',
    file_name: 'saas-quicklaunch-main.zip',
    file_size: '12.5 MB (Full Source Code)',
    tags: ['saas', 'boilerplate', 'source-code', 'nextjs', 'tailwind'],
    status: 'active',
    sales_count: 230,
    rating: 5.0,
    rating_count: 67,
    created_at: '2025-01-20T14:00:00Z',
    updated_at: '2025-01-20T14:00:00Z',
  },
  {
    id: 'prod-4',
    seller_id: 'user-seller-3',
    seller_name: 'Visual Tone Lab',
    name: 'Cinematic Moody Lightroom & Mobile Presets',
    slug: 'cinematic-moody-lightroom-presets',
    description: 'Paket 15 preset Lightroom Desktop (XMP) dan Mobile (DNG) dengan tone warm-cinematic dan analog film feeling. Cocok untuk fotografi street, travel, portrait, dan editorial content creator.',
    price: 89000,
    category: 'preset',
    thumbnail_url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    file_url: '/api/download/prod-4',
    file_name: 'Cinematic_Presets_Pack_XMP_DNG.zip',
    file_size: '34.8 MB (Presets + Guide)',
    tags: ['preset', 'lightroom', 'photography', 'creative', 'lut'],
    status: 'active',
    sales_count: 310,
    rating: 4.7,
    rating_count: 89,
    created_at: '2025-01-22T09:15:00Z',
    updated_at: '2025-01-22T09:15:00Z',
  },
  {
    id: 'prod-5',
    seller_id: 'user-seller-2',
    seller_name: 'Studio Minimal',
    name: 'Ultimate Solopreneur Notion OS 2025',
    slug: 'ultimate-solopreneur-notion-os',
    description: 'Satu dashboard terpadu di Notion untuk mengelola seluruh bisnis solo: CRM klien, content planner, invoice tracker, revenue streams, project milestones, dan knowledge repository.',
    price: 119000,
    category: 'template',
    thumbnail_url: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=800&q=80',
    file_url: '/api/download/prod-5',
    file_name: 'Solopreneur_OS_Notion_Access.zip',
    file_size: '4.2 MB (Template Link + Video Guide)',
    tags: ['notion', 'template', 'productivity', 'solopreneur', 'crm'],
    status: 'active',
    sales_count: 405,
    rating: 4.9,
    rating_count: 112,
    created_at: '2025-01-25T11:45:00Z',
    updated_at: '2025-01-25T11:45:00Z',
  },
  {
    id: 'prod-6',
    seller_id: 'user-seller-3',
    seller_name: 'Visual Tone Lab',
    name: '3D Clay Icon Pack - 140+ High-Res Assets',
    slug: '3d-clay-icon-pack',
    description: '140+ ikon 3D bergaya clay / soft modern dengan resolusi ultra 3000x3000px transparan PNG serta source file Blender (.blend) lengkap dengan material lighting setup siap render.',
    price: 189000,
    category: 'ui-kit',
    thumbnail_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    file_url: '/api/download/prod-6',
    file_name: '3D_Clay_Icons_Blender_PNG.zip',
    file_size: '210.5 MB (Blender + PNG)',
    tags: ['3d', 'icons', 'blender', 'ui-design', 'assets'],
    status: 'active',
    sales_count: 154,
    rating: 4.8,
    rating_count: 41,
    created_at: '2025-01-28T16:20:00Z',
    updated_at: '2025-01-28T16:20:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    product_id: 'prod-1',
    user_id: 'buyer-demo',
    user_name: 'Budi Santoso',
    rating: 5,
    comment: 'Penjelasan di e-book ini to-the-point dan arsitekturnya langsung bisa saya pakai di client project saya. Sangat worth it!',
    created_at: '2025-02-01T10:00:00Z',
  },
  {
    id: 'rev-2',
    product_id: 'prod-1',
    user_id: 'buyer-demo-2',
    user_name: 'Rian Pratama',
    rating: 5,
    comment: 'Sangat terstruktur, bonus source codenya rapi dan gampang dipelajari untuk pemula maupun mid-level developer.',
    created_at: '2025-02-03T14:30:00Z',
  },
  {
    id: 'rev-3',
    product_id: 'prod-2',
    user_id: 'buyer-demo',
    user_name: 'Sarah Wijaya',
    rating: 5,
    comment: 'Komponen figmanya luar biasa rapi. Auto-layoutnya konsisten dan hemat waktu berhari-hari saat ngerjain project dashboard!',
    created_at: '2025-02-05T09:20:00Z',
  },
  {
    id: 'rev-4',
    product_id: 'prod-3',
    user_id: 'buyer-demo-3',
    user_name: 'Dimas Anggoro',
    rating: 5,
    comment: 'Boilerplate SaaS terbaik yang pernah saya beli di platform lokal. Setup env langsung jalan tanpa error.',
    created_at: '2025-02-07T16:45:00Z',
  },
];
